project:
  type: website
  output-dir: docs

website:
  title: "Kazi Tanvir Hasan"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: CV.qmd
        text: Resume
      - href: certificate.qmd
        text: Certificate
      
format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual

